# Generated by Django 5.1.1 on 2024-10-31 20:08

import barbara_app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(default=0)),
                ('cpf', models.CharField(default='00000000000', max_length=11, unique=True)),
                ('nome', models.CharField(default='Sem Nome', max_length=100)),
                ('sexo', models.CharField(default='Nao Informado', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(default='Sem Telefone', max_length=15)),
                ('nome_social', models.CharField(default='Sem Nome Social Informado', max_length=100)),
                ('profissao', models.CharField(default='Nao Informado', max_length=100)),
                ('relacao_vitima', models.BooleanField(default=False)),
                ('mora_com_vitima', models.BooleanField(default=False)),
                ('filhos_vitima', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_agressores/')),
                ('ficha_criminal', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_destinatario', models.CharField(max_length=100)),
                ('email_remetente', models.EmailField(default='Denuncia Anonima', max_length=254)),
                ('telefone_remetente', models.CharField(default='Denuncia Anonima', max_length=15)),
                ('nome_remetente', models.CharField(default='Denuncia Anonima', max_length=100)),
                ('nome_destinatario', models.CharField(blank=True, default='Nao Informado', max_length=100, null=True)),
                ('assunto', models.CharField(default='Nao Informado', max_length=100)),
                ('conteudo', models.TextField(default='Não informado')),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/', validators=[barbara_app.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100)),
                ('nome_destinatario', models.CharField(blank=True, default='Nao Informado', max_length=100, null=True)),
                ('assunto', models.CharField(default='Nao Informado', max_length=100)),
                ('conteudo', models.TextField(default='Não informado')),
                ('email_remetente', models.EmailField(default='Nao Informado', max_length=254)),
                ('telefone_remetente', models.CharField(default='Nao Informado', max_length=15)),
                ('nome_remetente', models.CharField(default='Nao Informado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaContatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_nome', models.CharField(default='Sem Nome', max_length=100)),
                ('contato_telefone', models.CharField(default='Sem Telefone', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sem Nome', max_length=100)),
                ('nome_social', models.CharField(default='Sem Nome Social Informado', max_length=100)),
                ('data_nascimento', models.DateField(default='2000-01-01')),
                ('cidade_nascimento', models.CharField(default='Nao Informado', max_length=100)),
                ('estado_nascimento', models.CharField(default='Nao Informado', max_length=100)),
                ('cpf', models.CharField(default='00000000000', max_length=11, unique=True)),
                ('rg', models.CharField(default='0000000000', max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('endereco', models.TextField(default='Endereço não informado')),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(default='Sem Telefone', max_length=15)),
                ('estado_atual', models.TextField(default='Estado atual não informado')),
                ('medida_protetiva', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_vitimas/')),
                ('lista_contatos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='barbara_app.listacontatos')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_crime', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, default='Descrição não informada', null=True)),
                ('data_ocorrencia', models.DateField(default=django.utils.timezone.now)),
                ('localizacao', models.TextField(default='Endereço não informado')),
                ('medidas_preventivas', models.CharField(default='Nao Necessaria', max_length=200)),
                ('agressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='barbara_app.agressor')),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='barbara_app.vitima')),
            ],
        ),
        migrations.CreateModel(
            name='BotaoPanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrido', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('localizacao', models.TextField(default='Endereço não informado')),
                ('telefone_vitima', models.CharField(default='Sem Telefone', max_length=15)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbara_app.vitima')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim_Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='evidencias/', validators=[barbara_app.models.validate_file_extension])),
                ('agressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletim_ocorrencia', to='barbara_app.agressor')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_ocorrencia', to='barbara_app.ocorrencia')),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_ocorrencia', to='barbara_app.vitima')),
            ],
        ),
        migrations.AddField(
            model_name='agressor',
            name='ultima_vitima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbara_app.vitima'),
        ),
        migrations.AddField(
            model_name='agressor',
            name='vitimas',
            field=models.ManyToManyField(blank=True, related_name='agressores', to='barbara_app.vitima'),
        ),
    ]
