# Generated by Django 5.1.1 on 2024-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim_ocorrencia',
            name='agressor',
        ),
        migrations.RemoveField(
            model_name='boletim_ocorrencia',
            name='evidencias',
        ),
        migrations.RemoveField(
            model_name='boletim_ocorrencia',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='boletim_ocorrencia',
            name='vitima',
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='bairro_vitima',
            field=models.CharField(default='Bairro não informado', max_length=105),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='cep_vitima',
            field=models.CharField(default='00000-000', max_length=15),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='cidade_nascimento_vitima',
            field=models.CharField(default='Desconhecida', max_length=55),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='cidade_vitima',
            field=models.CharField(default='Cidade não informada', max_length=105),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='complemento_vitima',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='cpf_vitima',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='data_fato',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='data_nascimento_vitima',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='descricao_detalhada_ocorrido',
            field=models.TextField(default='Descrição não informada'),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='email_agressor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='email_vitima',
            field=models.EmailField(default='nao-informado@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='endereco_vitima',
            field=models.CharField(default='Endereço não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='estado_nascimento_vitima',
            field=models.CharField(default='Desconhecido', max_length=55),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='hora_fato',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='is_estrangeira_vitima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='local_fato',
            field=models.CharField(default='Local não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='medidas_protetivas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='mora_com_vitima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='nome_completo_agressor',
            field=models.CharField(default='Desconhecido', max_length=105),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='nome_completo_vitima',
            field=models.CharField(default='Desconhecido', max_length=105),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='nome_social_agressor',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='nome_social_vitima',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='possui_filhos_agressor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='profissao_agressor',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='relacionamento_vitima_agressor',
            field=models.CharField(default='Desconhecido', max_length=55),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='rg_vitima',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='sexo_agressor',
            field=models.CharField(default='Desconhecido', max_length=15),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='telefone_agressor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='telefone_familiar_amigo_vitima',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='telefone_vitima',
            field=models.CharField(default='00000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='boletim_ocorrencia',
            name='tipo_ocorrencia',
            field=models.CharField(default='Violencia Fisica', max_length=40),
        ),
    ]
