# Generated by Django 5.1.1 on 2024-11-05 17:14

import barbara_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0002_remove_boletim_ocorrencia_agressor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim_ocorrencia',
            name='evidencias',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', validators=[barbara_app.models.validate_file_extension]),
        ),
    ]
