# Generated by Django 5.1.1 on 2024-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0004_alter_boletim_ocorrencia_medidas_protetivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim_ocorrencia',
            name='medidas_protetivas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
