# Generated by Django 5.1.1 on 2024-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0005_alter_boletim_ocorrencia_medidas_protetivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim_ocorrencia',
            name='medidas_protetivas',
            field=models.CharField(default='Nao necessarias', max_length=255),
        ),
    ]
